version: 1.0.{build}
image:
- Visual Studio 2015
build:
  parallel: true
platform:
  - x64
environment:
  CONDA_DIR: C:\Miniconda36-x64
  matrix:
  - CONFIG: Debug
  - CONFIG: Release
init:
  - set PATH=%CONDA_DIR%;%CONDA_DIR%\Scripts;%CONDA_DIR%\Library\bin;%PATH%
install:
  - conda config --system --set always_yes yes --set changeps1 no
  - conda config --system --append channels conda-forge
  - conda install -n base conda-devenv
  - conda devenv
  - call activate reaktoro
  - conda list
build_script:
  - inv -e compile
  - python ci\check_compiled_files.py
test_script:
  - pytest -n auto -ra -vv tests/regression -k test_equilibrium_path.py --color=yes
